Support passing display name on version POST/PUT
adobe/da-admin pull request #38
Opened 2024-04-30 15:55 UTC by bosschaert

## Description

Make it possible to provide a version display name on the initial version POST/PUT.

## Related Issue

#6

## How Has This Been Tested?

* Tested locally.
* Unit tests in the making, will be added to this PR.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-05-01 22:41 UTC, auniverseaway requested changes
I think AEM is right here and would probably lean towards building something familiar...

I would say, `label` instead of `displayname`. This is how we would expose it in the UI.

<img width="359" alt="Screenshot 2024-05-01 at 4 39 05 PM" src="https://github.com/adobe/da-admin/assets/1972095/ac56df6c-a9f6-4065-878d-1d993798a861">

2024-05-02 09:46 UTC, bosschaert commented
Thanks @auniverseaway I agree `label` is better so I changed it to that and also added `comment`.

2024-05-03 03:34 UTC, auniverseaway approved these changes

2024-05-03 03:49 UTC, auniverseaway commented
@bosschaert I approved, but I would remove the comment part. I wouldn't build that out until someone asks for it. Label should do for the foreseeable future and we can always add comment back in later.

2024-05-03 09:13 UTC, karlpauls approved these changes

2024-05-03 09:28 UTC, merged